---
- name: "VPS Nook | Hardening"
  hosts: vps
  gather_facts: yes
  become: yes
  roles:
    - role: vps_hardening
      tags: [hardening]

- name: "VPS Nook | Orchestration"
  hosts: vps
  gather_facts: yes
  become: yes
  roles:
    - role: vps_orchestration
      tags: [orchestration]
